title: "Shreyanth Portfolio"
logo: "/assets/img/IMG_5772.PNG"
description: >
  I am a data science enthusiast passionate about solving complex problems, connecting ideas across domains, 
  and developing innovative solutions that balance theoretical intelligence with real-world usability in limited-resource settings.
