title: Shreyanth Portfolio
logo: /assets/img/Shreyanth_hg.jpg
description: Hi there Im an aspiring data science enthusiastic who loves finding patterns and connecting dots: be it ideas from different industries, people from different backgrounds and teams, or applications from different industries. I have good technical skills, particularly in databases and machine learning, and an academic background in mathematics, engineering and statistics.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
